# Generated by Django 2.0.3 on 2018-06-01 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('unique_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='User', max_length=30, unique=True)),
                ('mail', models.EmailField(max_length=254, null=True, unique=True)),
                ('slacktoken', models.CharField(max_length=100, null=True)),
                ('slackchannel', models.CharField(max_length=50, null=True)),
                ('role', models.IntegerField(choices=[(0, 'USER'), (1, 'ADMIN')], default=0)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('domain', models.IntegerField(choices=[(0, 'BASE'), (1, 'UHASSELT'), (2, 'CEGEKA')], default=0)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Calendars',
            fields=[
                ('cal_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cal_alias', models.CharField(blank=True, max_length=30, null=True)),
                ('cal_color', models.CharField(choices=[(0, 'Blue'), (1, 'Red')], default='Blue', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Calendars',
            },
        ),
        migrations.CreateModel(
            name='CalendarSources',
            fields=[
                ('cal_source_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cal_source_alias', models.CharField(default='Source', max_length=30)),
                ('source_location', models.FilePathField()),
                ('filtered_source_location', models.FilePathField()),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[(0, 'File'), (1, 'URL')], default='File', max_length=200)),
                ('cal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal_tool.Calendars')),
            ],
            options={
                'verbose_name_plural': 'CalendarSources',
            },
        ),
        migrations.CreateModel(
            name='FilterAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Location'), (1, 'Summary'), (2, 'Description'), (3, 'Start'), (4, 'End'), (5, 'Status'), (6, 'Class'), (7, 'Priority'), (8, 'Organizer'), (9, 'Prof'), (10, 'Course'), (11, 'CourseNumber'), (12, 'Room'), (13, 'Type'), (14, 'Group')], default='Description', max_length=200)),
                ('mode', models.CharField(choices=[(15, 'Contains'), (16, 'Equal')], default='Contains', max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('not_value', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'FilterAttributes',
            },
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('filter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('cal_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal_tool.CalendarSources')),
            ],
            options={
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='SharedCalendars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50, null=True, unique=True)),
                ('url', models.URLField(unique=True)),
                ('password', models.CharField(max_length=200)),
                ('cal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal_tool.Calendars')),
            ],
            options={
                'verbose_name_plural': 'SharedCalendars',
            },
        ),
        migrations.CreateModel(
            name='PasswordTokens',
            fields=[
                ('unique_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password_token', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'PasswordTokens',
            },
        ),
        migrations.AddField(
            model_name='filterattributes',
            name='filter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal_tool.Filters'),
        ),
        migrations.AddField(
            model_name='calendars',
            name='unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
