#!/bin/bash

script_name=$0
script_directory=$(dirname "$0")
user_directory=$(pwd)
cd $script_directory

docker-compose exec web python3 manage.py makemigrations 
docker-compose exec web python3 manage.py migrate 
docker-compose exec web python3 manage.py createsuperuser

cd $user_directory



