#!/bin/bash

script_name=$0
script_directory=$(dirname "$0")
user_directory=$(pwd)
cd $script_directory

docker-compose down 
docker-compose up -d
docker-compose exec web sh -c crond


cd $user_directory