web:
  restart: always
  build: ./web/
  ports:
    - 8000:8000
  links:
    - postgres:postgres
    - redis:redis
  env_file: env
  volumes:
    - ./web:/data/web
  volumes_from:
    - db_data
  command: /usr/bin/gunicorn Project.wsgi:application -w 2 -b :8000 

nginx:
  restart: always
  build: ./nginx/
  ports:  
    - 80:80
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  build: ./postgres/
  volumes_from:
    - db_data
  volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  env_file:
    - env
  ports:
    - 5432:5432

redis:
  restart: always
  image: redis:4.0.9
  ports:
    - 6379:6379

db_data:
  restart: always
  build: ./db_data/
  volumes:
    - ./db_data:/var/lib/postgresql
  command: "true"

